name: "Terraform Apply"
description: "Runs a terraform apply in the given workspace with the given vars file"
inputs:
  workspace:
    description: "The terraform workspace to run in. Usually a region, like us-west-2"
    requied: true
  varfile:
    description: "The vars file to pass to terraform"
    required: true
  terraform_dir:
    description: "Path to terraform directory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Init
      working-directory: ${{ inputs.terraform_dir }}
      run: terraform init
      shell: sh
    - name: Ensure workspace exists
      working-directory: ${{ inputs.terraform_dir }}
      run: |
        terraform workspace new ${{ inputs.workspace }} || true
      shell: sh
    - name: Select Workspace
      working-directory: ${{ inputs.terraform_dir }}
      run: terraform workspace select ${{ inputs.workspace }}
      shell: sh
    - name: Apply
      working-directory: ${{ inputs.terraform_dir }}
      run: terraform apply -auto-approve -var-file=${{ inputs.varfile }}
      shell: sh
