name: "Enforce Semantic Versioning"
description: "Ensures the current version/tag is compliant with `Major.minor.patch` formatting. Supports up to three digits per release type, and numerics/periods only. Suitable for runners with Bash."
runs:
  using: "composite"
  steps:
    - name: Check Versioning Compliance
      run: |
          set -e
          echo "Version $GITHUB_REF_NAME"
          IFS='.'
          tempHold=$GITHUB_REF_NAME
          verArray=($tempHold)
          echo "${verArray[0]}, ${verArray[1]}, ${verArray[2]}"
          if [[ ${#verArray[@]} -le 2 ]]
          then
            echo "The version number tagged in this release is two or fewer numbers. Please use a three-digit version number in the form of Major.minor.patch."
            exit 1
          elif [[ ${#verArray[@]} -gt 3 ]]
          then
            echo "The version number tagged in this release is three or more numbers. Please use a three-digit version number in the form of Major.minor.patch."
            exit 1
          else
            for i in "${verArray[@]}"
            do
              if ! [[ $i =~ ^[0-9]{1,3} ]]
              then
                echo "Please use only numbers in your versioning."
                exit 1
              fi
            done
          fi
      shell: sh
