name: test-activate-venv

on:
  push:
    branches:
    - main
    tags:
    - '**'
  pull_request:
    branches:
    - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/') || startsWith(github.ref, 'refs/heads/long_lived/')) && github.sha || '' }}
  cancel-in-progress: true

jobs:
  test:
    name: ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.runs-on }}
    container: ${{ matrix.os.container }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - name: macOS
            matrix: macos
            runs-on: macos-latest
          - name: Ubuntu
            matrix: ubuntu
            runs-on: ubuntu-latest
          - name: Ubuntu Docker
            matrix: docker
            runs-on: ubuntu-latest
            container: ubuntu
          - name: Windows
            matrix: windows
            runs-on: windows-latest
        python:
          - name: '3.9'
            action: '3.9'

    steps:
    - uses: actions/checkout@v3

    - name: Set up ${{ matrix.python.name }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python.action }}

    - name: Setup virtual environment
      run: |
        python -m venv venv

    - name: Run the action
      uses: ./activate-venv/

    - name: Check environment is activated
      env:
        EXPECTED_EXECUTABLE: ./venv/${{ matrix.os.name == 'windows' && 'Scripts' || 'bin' }}/${{ matrix.os.name == 'windows' && 'python.exe' || 'python' }}
      run: |
        python activate-venv/test_check_activated.py
